In [1]:
# 데이터 클리닝 유일성
import pandas as pd

In [2]:
df = pd.read_csv('data/dust.csv')
df.head()

,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,세종,경북,경남,제주,강원.1
0,08월 11일,7,17,15,10,29,12,12,9,16,14,16,25,21,11,14,24,21,16
1,08월 10일,15,25,15,20,28,25,17,20,16,25,29,29,25,27,14,29,23,16
2,08월 09일,24,26,26,27,27,27,22,27,25,32,24,24,27,26,25,38,25,25
3,08월 08일,26,25,28,26,29,31,20,26,29,33,26,29,31,31,28,32,27,29
4,08월 07일,20,26,22,25,33,24,18,23,18,23,29,33,29,27,19,28,26,18

In [3]:
df.drop_duplicates(inplace=True)

In [6]:
df.value_counts('날짜')

날짜
07월 13일    1
07월 14일    1
08월 10일    1
08월 09일    1
08월 08일    1
08월 07일    1
08월 06일    1
08월 05일    1
08월 04일    1
08월 03일    1
08월 02일    1
08월 01일    1
07월 31일    1
07월 30일    1
07월 29일    1
07월 28일    1
07월 27일    1
07월 26일    1
07월 25일    1
07월 24일    1
07월 23일    1
07월 22일    1
07월 21일    1
07월 20일    1
07월 19일    1
07월 18일    1
07월 17일    1
07월 16일    1
07월 15일    1
08월 11일    1
dtype: int64

In [9]:
df = df.T.drop_duplicates().T # 가로로 바꿔준뒤 중복되는 행 삭제후 다시 되돌린값을 df에 저장

In [10]:
df

,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,세종,경북,경남,제주
0,08월 11일,7,17,15,10,29,12,12,9,16,14,16,25,21,11,14,24,21
1,08월 10일,15,25,15,20,28,25,17,20,16,25,29,29,25,27,14,29,23
2,08월 09일,24,26,26,27,27,27,22,27,25,32,24,24,27,26,25,38,25
3,08월 08일,26,25,28,26,29,31,20,26,29,33,26,29,31,31,28,32,27
4,08월 07일,20,26,22,25,33,24,18,23,18,23,29,33,29,27,19,28,26
5,08월 06일,31,39,29,35,27,31,31,30,22,33,28,27,30,34,29,37,24
6,08월 05일,27,36,25,31,27,24,30,27,25,31,25,26,25,25,28,31,22
7,08월 04일,27,36,26,31,27,27,32,31,39,36,30,27,27,29,29,36,27
8,08월 03일,44,32,23,47,29,28,29,44,33,31,34,27,28,32,28,31,26
9,08월 02일,40,26,20,41,26,19,20,39,25,24,33,29,22,24,22,27,32
10,08월 01일,33,26,22,40,24,18,26,35,20,26,36,30,23,28,21,25,30
11,07월 31일,18,26,17,23,23,17,23,21,19,20,21,21,22,19,22,25,28
13,07월 30일,10,28,14,15,18,14,24,14,17,15,15,15,18,15,20,22,29
14,07월 29일,18,29,16,22,28,23,30,20,22,26,26,27,27,24,29,25,35
15,07월 28일,39,38,29,41,37,44,30,40,37,50,39,43,42,41,36,46,29
16,07월 27일,48,51,41,39,30,41,57,47,45,52,37,35,37,46,46,55,24
17,07월 26일,41,55,36,39,30,29,60,39,37,37,29,32,27,31,36,47,29
18,07월 25일,32,40,30,31,29,26,46,31,39,35,24,28,24,26,36,35,28
19,07월 24일,42,33,31,37,20,33,44,42,39,49,31,22,21,39,39,30,23
20,07월 23일,31,31,25,28,21,26,33,35,41,37,26,22,22,31,27,30,24
21,07월 22일,30,28,20,30,21,40,26,34,44,48,39,36,22,46,26,29,30
22,07월 21일,37,37,41,30,48,57,42,38,51,59,40,59,43,56,49,43,39
23,07월 20일,36,70,56,27,46,44,77,36,44,51,33,44,54,44,61,68,46
24,07월 19일,30,76,54,29,36,40,81,32,40,47,28,35,39,35,55,66,26
25,07월 18일,35,55,42,36,39,42,66,36,39,47,32,35,35,42,47,53,28
26,07월 17일,30,56,49,32,38,36,65,32,44,43,30,32,43,38,49,55,37
27,07월 16일,26,48,42,24,37,30,59,28,36,38,23,25,34,32,36,47,36
28,07월 15일,22,49,21,22,23,18,55,23,25,24,17,19,22,20,25,41,27
29,07월 14일,20,46,26,22,24,17,54,21,26,23,16,19,20,18,26,39,21
30,07월 13일,21,43,29,19,23,19,47,21,24,24,15,21,21,19,26,38,23